# Generated by Django 6.0.5 on 2026-05-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actorportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodata',
            name='actor_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
