# Generated by Django 6.0.5 on 2026-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actorportfolio', '0002_portfoliodata_actor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodata',
            name='about_image',
            field=models.ImageField(default='exit', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
