# Generated by Django 6.0.5 on 2026-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actorportfolio', '0003_portfoliodata_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodata',
            name='about_description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
